name: Parse DNS
on:
  workflow_run:
    workflows: ["TG"]  # Name of the primary workflow
    types:
      - completed  # Trigger only when the primary workflow is completed
    branches: [main] 
  workflow_dispatch:

jobs:
  parse-dns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clear output files
        run: |
          : > dns/dns.txt
          : > dns/dns_.txt

      - name: Run parser
        run: python dns/dns.py

      - name: Local Authentication
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
  
      - name: Commit & push Parser
        run: |
          git add .
          timestamp=$(TZ='Asia/Tehran' date)
          git commit -m "✅List updated ${timestamp}"
          git pull
          git push
